### ISSUE TITLE
Swagger definition route should be customizable

### ISSUE THREAD

**Issue by Zizaco** [ahmadarif/adonis-swagger#3]
Currently the route `GET /swagger.json` is hardcoded. https://github.com/ahmadarif/adonis-swagger/blob/master/providers/SwaggerProvider.js#L16

It would be very helpful (and necessary in my current project) to be able to change that route of the config file.

**Comment by ahmadarif** [comment]
@Zizaco sorry for my late reply, there are currently no function to change the route.

If you would like try to implement this and open a pull request, I would be happy to review and accept it. 🙂

**Comment by ahmadarif** [comment]
Fix in this PR
https://github.com/ahmadarif/adonis-swagger/pull/6
