### ISSUE TITLE
Support for api versions (Feature Request)

### ISSUE THREAD

**Issue by willvincent** [ahmadarif/adonis-swagger#4]
It's possible, and I think fairly common, to allow versioning an api with route groups:

ie: `api/v1/[blah]` and `api/v2/[blah]`

Would be nice if there were a good way to restrict what's included in the swagger doc by these versioned routes, so that one could generate a swagger doc for the v1 routes and a separate one for v2 routes.

**Comment by ahmadarif** [comment]
If you would like try to implement this and open a pull request, I would be happy to review and accept it. 🙂

**Comment by ahmadarif** [comment]
Maybe you can use custom API route, but still can't use API versioning.
https://github.com/ahmadarif/adonis-swagger/pull/10

**Comment by willvincent** [comment]
I don't know why you would close it with reference to that other issue, that's not really a solution. The swagger spec supports versions, one shouldn't have to maintain multiple swagger definition files.

**Comment by raraujosilva** [comment]
It would be wonderful if it had api versioning, every successful api project should have it.
