### ISSUE TITLE
Can't read from file /swagger.json

### ISSUE THREAD

**Issue by prawee** [ahmadarif/adonis-swagger#5]
i'm using configure from original repo is working. but exist error at right bottom "ERROR"

**Comment by ahmadarif** [comment]
Please screenshot the error log and routing file.

**Comment by prawee** [comment]
on link of docs
<img width="1067" alt="screen shot 2561-09-24 at 11 11 59" src="https://user-images.githubusercontent.com/3203937/45937491-c8fbd580-bfea-11e8-9926-81884ba8bb8c.png">

when did i click it
<img width="799" alt="screen shot 2561-09-24 at 11 12 13" src="https://user-images.githubusercontent.com/3203937/45937494-cd27f300-bfea-11e8-827c-63f4532da474.png">

**Comment by lysla** [comment]
Identical issue for me.
There is a reference in the auto generated swagger.js to
```
 specUrl: '/swagger.json',
```
But that file doesn't exists anywhere I think 🤔

----

Edit => the actual reference is in the generated public/docs/index.html

```
window.onload = function() {
  
  // Build a system
  const ui = SwaggerUIBundle({
    url: "/swagger.json",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
```

**Comment by lysla** [comment]
Fixed that, it was missing the full reference to absolute url 🎉

```
url: "http://127.0.0.1:3333/swagger.json"
```

Of course would be best finding a way to dynamically add the absolute path, since that won't work in production.

**Comment by prawee** [comment]
@lysla  not working bro.

<img width="1116" alt="screen shot 2561-12-06 at 11 04 29" src="https://user-images.githubusercontent.com/3203937/49560892-e6ccab80-f946-11e8-995a-70d6dc50ee7f.png">

**Comment by ahmadarif** [comment]
Hi @prawee, sorry for the late reply.
Swagger file explorer must be like this
![image](https://user-images.githubusercontent.com/10185374/50751381-20f9d780-127c-11e9-8062-cdf4ba552374.png)

**Comment by ahmadarif** [comment]
Please update your library to v1.3.0

**Comment by prawee** [comment]
thank you @ahmadarif

**Comment by ahmadarif** [comment]
you're welcome 👍

**Comment by spotontheresa** [comment]
Hi! I'd like to ask when would version 1.3.0 be released? The latest is 1.2.9 and the same error still exists. Thanks!

Serving at `127.0.0.1:3000/docs/`

**Comment by IlyaSovenko** [comment]
@ahmadarif can you update your package on npm to version 1.3.0, please?)

**Comment by franciskisiara** [comment]
I solved this problem by exporting the configuration file using the command:
`adonis swagger:export`

EDIT: But then upon editing the swagger.js config file, the issue arose. :(

**Comment by syntaxlexx** [comment]
On my end, running `adonis swagger:export` reset the `swagger.json` config file afresh! I believe that should not be the case; I stand to be corrected
