### ISSUE TITLE
Customize docs path name (Feature request)

### ISSUE THREAD

**Issue by renzosunico** [ahmadarif/adonis-swagger#9]
Hi,

We are currently using ALB for our services. Each microservice is in a path.
For example:

- www.microservices.com/microservice1
- www.microservices.com/microservice2

It would be helpful for us if we could change the path of the docs to:

- www.microservices.com/microservice1/docs
- www.microservices.com/microservice2/docs

Instead of:

- www.microservices.com/docs

Thank you!

**Comment by ahmadarif** [comment]
Fix in this PR https://github.com/ahmadarif/adonis-swagger/pull/10
